[server]
host = "127.0.0.1"
port = 3100

[site]
title = "Polaris"

[theme]
active = "default"
dir = "themes"

[security]
secret = "demo7clu59omrwyqntki6djzx128f0ape"

[database]
driver = "sqlite"
url = "data-demo/polaris.db"
max_connections = 5

[cache]
enabled = true
driver = "memory"

[setup]
env_done = true
