server:
    addr: :8080
    mode: release
database:
    driver: sqlite
    dsn: polaris.db
cache:
    driver: redis
    ttl: 3600
    redis:
        addr: redis-19168.c60.us-west-1-2.ec2.cloud.redislabs.com:19168
        password: vvCtZMffjHOorH0zlKvCsHIolqFo4kZy
        db: 0
security:
    secret_key: 8b9bb48732e12d03c95da1270e2c6d53c5133655f55f04463f8da605134d9b3d
    session_name: polaris_session
    csrf_enabled: true
